# Generated by Django 6.0.1 on 2026-01-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_designimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesignImage',
        ),
    ]
