# Generated by Django 6.0.1 on 2026-01-26 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
        ('reports', '0003_delete_designimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_as_image_1', to='designs.designimage'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_as_image_2', to='designs.designimage'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='verdict',
            field=models.CharField(max_length=100),
        ),
    ]
