# Generated by Django 6.0.1 on 2026-01-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
